var DEFAULT_SETTINGS = {
  "DebugMode": false,
  "Command": "!link",
  "CommandMessage": "Get The Game Now: ",
  "ResponseMessage": "You can get '$epicGame' and support this channel by going to $epicLink",
  "CreatorCode": "",
  "CreatorCodeId": "",
  "DisplaySeconds": 10,
  "BetweenAdDelay": 10,
  "InTransition": "slideInRight",
  "InAttentionAnimation": "pulse",
  "OutTransition": "slideOutRight",
  "OutAttentionAnimation": "pulse",
  "Opacity": 0,
  "FontName": "days-one",
  "CustomFontName": "",
  "BackgroundColor": "rgba(0,0,0,1)",
  "BackgroundImage": "",
  "BackgroundVideo": "",
  "ImageBackgroundColor": "rgba(0,0,0,1)",
  "ForegroundColor": "rgba(255,255,255,1)",
  "CommandColor": "rgba(153, 74, 0, 1)",
  "OutlinedColor": "rgba(0,0,0,1)",
  "TitleFontSize": 2,
  "HelpFontSize": 1.5,
  "BoxBorderRadiusTopRight": 0,
  "BoxBorderRadiusTopLeft": 0,
  "BoxBorderRadiusBottomRight": 0,
  "BoxBorderRadiusBottomLeft": 0,
  "IconMarginTop": 0,
  "IconMarginBottom": 0,
  "IconMarginRight": 12,
  "IconMarginLeft": 10,
  "TitleMarginTop": 16,
  "TitleMarginBottom": 0,
  "TitleMarginRight": 0,
  "TitleMarginLeft": 12,
  "HelpMarginTop": 0,
  "HelpMarginBottom": 0,
  "HelpMarginRight": 0,
  "HelpMarginLeft": 10,
  "CommandMarginTop": 0,
  "CommandMarginBottom": 0,
  "CommandMarginRight": 0,
  "CommandMarginLeft": 12
};